In [82]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [83]:
#Preprocesamiento
dataset = pd.read_csv('Churn_Modelling.csv')

In [84]:
dataset.head(10)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   
5          6    15574012       Chu          645     Spain    Male   44   
6          7    15592531  Bartlett          822    France    Male   50   
7          8    15656148    Obinna          376   Germany  Female   29   
8          9    15792365        He          501    France    Male   44   
9         10    15592389        H?          684    France    Male   27   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   
6       7       0.00              2          1               1   
7       4  115046.74              4          1               0   
8       4  142051.07              2          0               1   
9       2  134603.88              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1  
6         10062.80       0  
7        119346.88       1  
8         74940.50       0  
9         71725.73       0

In [85]:
X = dataset.iloc[:,3:13].values
y = dataset.iloc[:,13].values

In [86]:
labelencoder_X_1 = LabelEncoder()
X[:,1] = labelencoder_X_1.fit_transform(X[:,1])
labelencoder_X_2 = LabelEncoder()
X[:,2] = labelencoder_X_2.fit_transform(X[:,2])
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [87]:
for i in range(2):
    print(X[i])

[619 0 0 42 2 0.0 1 1 1 101348.88]
[608 2 0 41 1 83807.86 1 0 1 112542.58]


In [88]:
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()

In [64]:
for i in range(8):
    print(X[i])

[1.0000000e+00 0.0000000e+00 0.0000000e+00 6.1900000e+02 0.0000000e+00
 4.2000000e+01 2.0000000e+00 0.0000000e+00 1.0000000e+00 1.0000000e+00
 1.0000000e+00 1.0134888e+05]
[0.0000000e+00 0.0000000e+00 1.0000000e+00 6.0800000e+02 0.0000000e+00
 4.1000000e+01 1.0000000e+00 8.3807860e+04 1.0000000e+00 0.0000000e+00
 1.0000000e+00 1.1254258e+05]
[1.0000000e+00 0.0000000e+00 0.0000000e+00 5.0200000e+02 0.0000000e+00
 4.2000000e+01 8.0000000e+00 1.5966080e+05 3.0000000e+00 1.0000000e+00
 0.0000000e+00 1.1393157e+05]
[1.000000e+00 0.000000e+00 0.000000e+00 6.990000e+02 0.000000e+00
 3.900000e+01 1.000000e+00 0.000000e+00 2.000000e+00 0.000000e+00
 0.000000e+00 9.382663e+04]
[0.0000000e+00 0.0000000e+00 1.0000000e+00 8.5000000e+02 0.0000000e+00
 4.3000000e+01 2.0000000e+00 1.2551082e+05 1.0000000e+00 1.0000000e+00
 1.0000000e+00 7.9084100e+04]
[0.0000000e+00 0.0000000e+00 1.0000000e+00 6.4500000e+02 1.0000000e+00
 4.4000000e+01 8.0000000e+00 1.1375578e+05 2.0000000e+00 1.0000000e+00
 0.0000000

In [89]:
#Spliting the data in train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [90]:
#Feature Scaling
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [67]:
X_test.shape

(2000, 12)

In [94]:
#import the keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

In [95]:
#Inicialization the Neural-Network
classifier = Sequential()

In [96]:
#Adding the input layer and the first hidden layer
classifier.add(Dense(6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 12))
classifier.add(Dropout(0.1))
#Adding the second hidden layer
classifier.add(Dense(6, kernel_initializer = 'uniform', activation = 'relu'))
classifier.add(Dropout(0.1))

In [97]:
#Adding hte output layer
classifier.add(Dense(1, kernel_initializer='uniform', activation = 'sigmoid'))

In [98]:
#Compile ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [99]:
classifier.fit(X_train, y_train, batch_size=25, nb_epoch=100)

/home/diegojavier/.local/lib/python3.5/site-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Epoch 1/100
8000/8000 [==============================] - 3s 326us/step - loss: 0.5542 - acc: 0.7950
Epoch 2/100
8000/8000 [==============================] - 0s 52us/step - loss: 0.4452 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 0s 52us/step - loss: 0.4367 - acc: 0.7960
Epoch 4/100
8000/8000 [==============================] - 0s 53us/step - loss: 0.4334 - acc: 0.7960
Epoch 5/100
8000/8000 [==============================] - 0s 52us/step - loss: 0.4341 - acc: 0.7960
Epoch 6/100
8000/8000 [==============================] - 0s 53us/step - loss: 0.4303 - acc: 0.7960
Epoch 7/100
8000/8000 [==============================] - 0s 53us/step - loss: 0.4317 - acc: 0.7960
Epoch 8/100
8000/8000 [==============================] - 0s 53us/step - loss: 0.4304 - acc: 0.7960
Epoch 9/100
8000/8000 [==============================] - 0s 53us/step - loss: 0.4278 - acc: 0.7960
Epoch 10/100
8000/8000 [==============================] - 0s 55us/step - loss: 0.4311 - acc: 0.7960
Epoch 11

Epoch 83/100
8000/8000 [==============================] - 0s 51us/step - loss: 0.4142 - acc: 0.8295
Epoch 84/100
8000/8000 [==============================] - 1s 63us/step - loss: 0.4172 - acc: 0.8275
Epoch 85/100
8000/8000 [==============================] - 1s 71us/step - loss: 0.4168 - acc: 0.8275
Epoch 86/100
8000/8000 [==============================] - 0s 62us/step - loss: 0.4108 - acc: 0.8320
Epoch 87/100
8000/8000 [==============================] - 1s 91us/step - loss: 0.4167 - acc: 0.8285
Epoch 88/100
8000/8000 [==============================] - 0s 62us/step - loss: 0.4136 - acc: 0.8286
Epoch 89/100
8000/8000 [==============================] - 0s 56us/step - loss: 0.4157 - acc: 0.8269
Epoch 90/100
8000/8000 [==============================] - 1s 63us/step - loss: 0.4155 - acc: 0.8296
Epoch 91/100
8000/8000 [==============================] - 0s 57us/step - loss: 0.4114 - acc: 0.8310
Epoch 92/100
8000/8000 [==============================] - 0s 56us/step - loss: 0.4146 - acc: 0.8329


In [100]:
#Predict de result
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [101]:
for i in range(20):
    print(y_pred[i])

[False]
[False]
[False]
[False]
[False]
[ True]
[False]
[False]
[False]
[ True]
[False]
[False]
[False]
[False]
[ True]
[False]
[False]
[False]
[False]
[False]


In [102]:
for i in range(20):
    print(y_test[i])

0
1
0
0
0
1
0
0
1
1
0
0
0
0
1
1
0
0
0
0


In [103]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [104]:
cm

array([[1549,   46],
       [ 261,  144]])

In [105]:
(1549+144)/2000

0.8465

In [53]:
#Estimando el valor de 1 instancia
new_prediction = classifier.predict(sc.transform(np.array([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))

In [54]:
new_prediction = (new_prediction>0.5)
new_prediction

array([[False]])

In [55]:
#Evaluating the ANN
from keras.wrappers.scikit_learn import  KerasClassifier
from sklearn.model_selection import cross_val_score

def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 12))
    #Adding the second hidden layer
    classifier.add(Dense(6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(1, kernel_initializer='uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    
    return classifier


In [81]:
classifier = KerasClassifier(build_fn = build_classifier, batch_size=10, nb_epoch=100)
cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10, n_jobs = -1)

Epoch 1/1
Epoch 1/1
Epoch 1/1
Epoch 1/1
Epoch 1/1
Epoch 1/1
Epoch 1/1
Epoch 1/1


KeyboardInterrupt: 

In [ ]:
#Falta evaluar
mean = accuracies.mean()
variance = acccuracies.std()

In [92]:
#Improving the ANN
from keras.wrappers.scikit_learn import  KerasClassifier
from sklearn.model_selection import GridSearchCV

def build_classifier(optimizer):
    classifier = Sequential()
    classifier.add(Dense(6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 12))
    #Adding the second hidden layer
    classifier.add(Dense(6, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(1, kernel_initializer='uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = optimizer, loss = 'binary_crossentropy', metrics = ['accuracy'])
    
    return classifier

classifier = KerasClassifier(build_fn = build_classifier)
parameters = {'batch_size': [25, 32],
             'nb_epoch': [100, 500], 
             'optimizer': ['adam', 'rmsprop']}

grid_search = GridSearchCV(estimator = classifier, 
                          param_grid = parameters,
                          scoring = 'accuracy',
                          cv = 10)

grid_search = grid_search.fit(X_train, y_train)
best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_

Epoch 1/1
7200/7200 [==============================] - 0s 54us/step - loss: 0.5581 - acc: 0.7949
Epoch 1/1
7200/7200 [==============================] - 0s 58us/step - loss: 0.5625 - acc: 0.7964
Epoch 1/1
7200/7200 [==============================] - 0s 61us/step - loss: 0.5615 - acc: 0.7956
Epoch 1/1
7200/7200 [==============================] - 0s 69us/step - loss: 0.5627 - acc: 0.7961
Epoch 1/1
7200/7200 [==============================] - 0s 66us/step - loss: 0.5720 - acc: 0.7917
Epoch 1/1
7200/7200 [==============================] - 1s 81us/step - loss: 0.5521 - acc: 0.7942
Epoch 1/1
7200/7200 [==============================] - 1s 74us/step - loss: 0.5612 - acc: 0.7953
Epoch 1/1
7200/7200 [==============================] - 1s 85us/step - loss: 0.5484 - acc: 0.7960
Epoch 1/1
7200/7200 [==============================] - 1s 88us/step - loss: 0.5528 - acc: 0.7957
Epoch 1/1
7200/7200 [==============================] - 1s 91us/step - loss: 0.5602 - acc: 0.7946
Epoch 1/1
7200/7200 [=========

In [93]:
best_parameters

{'batch_size': 25, 'nb_epoch': 100, 'optimizer': 'adam'}